day73__/blog/models.py
from django.db import models
import os

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk - 1}]{self.title}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().rsplit('.', maxsplit=1)[-1]

day73__/blog/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView, DetailView


# Create your views here.
# def index(request):
#     posts = Post.objects.all().order_by('-pk')
#     return render(
#         request,
#         "blog/index.html",
#         {
#             "posts": posts,
#         }
#     )

# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)

#     return render(
#         request,
#         "blog/single_post_page.html",
#         {
#             "post": post,
#         }
#     )


class PostList(ListView):
    model = Post
    ordering = '-pk'


class PostDetail(DetailView):
    model = Post
    

day73__/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>Blog</title>
        <script src="https://kit.fontawesome.com/070fdd1afb.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">

    </head>
    <body>
        
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Do It Django</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                          </li>
                        <li class="nav-item">
                        <a class="nav-link" href="#">Blog</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="#">About Me</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Download link
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Log In</button>
                        </li>
                        </ul>
                    </ul>
                </div>
            </div>
        </nav>
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">welcome !</h1>
                    <p class="lead mb-0">2025-02-23 아펠가모 선릉</p>
                </div>
            </div>
        </header>
        <div class="modal fade" id="exampleModal" tabindex="-1">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title"><i class="fa-solid fa-right-to-bracket"></i>Log In</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="row"> 
                    <div class="col-md-6">
                        <button type="button" class="btn btn-outline-dark btn-block btn-sm"><i class="fa-solid fa-house"></i> Log in with Google</button>
                        <button type="button" class="btn btn-outline-dark btn-block btn-sm"><i class="fa-solid fa-house"></i> Log in with E-mail</button>
                    </div>
                    <div class="col-md-6">
                        <button type="button" class="btn btn-outline-dark btn-block btn-sm"><i class="fa-solid fa-house"></i> Sign Up with E-mail</button>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
        </div>
        <div class="container" id="main-area">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    {% block main_area %}
                    {% endblock %}
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <h1>Blog</h1>
        
        <!-- {% for post in post_list %}
            <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
            <h4>{{post.created_at}}</h4>
        {% endfor %} -->

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

day73__/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block main_area %}
<!-- Post content-->
<div id="post-area">
  <article>
      <!-- Post header-->
      <header class="mb-4">
          <!-- Post title-->
          <h1 class="fw-bolder mb-1 mt-5">{{ post.title }}</h1>
          <!-- Post meta content-->
          <div class="text-muted fst-italic mb-2">{{ post.created_at }}</div>
          <!-- Post categories-->
          <a class="badge bg-secondary text-decoration-none link-light" href="#!"> 정치 </a>
          <p class="lead"> by <a href="#"> TBC</a></p>
      </header>
      <!-- Preview image figure-->
      {% if post.head_image %}
      <figure class="mb-4"><img class="img-fluid rounded" src="{{post.head_image}}" alt="..." /></figure>
      {% else %}
      <figure class="mb-4"><img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.id}}/600/300" alt="..." /></figure>
      {% endif %}
      <!-- Post content-->
      <section class="mb-5">
          <p class="fs-5 mb-4"> {{post.content}} </p>
      </section>
      <!-- download button -->
    {% if post.file_upload %}
        <a type="button" href="{{post.file_upload.url}}">Download:
      {% if post.get_file_ext == 'zip' %}
          <i class="fa-solid fa-file-zipper"></i>

      {% elif post.get_file_ext == 'csv' or post.get_file_ext == 'xls' or post.get_file_ext == 'xlsx'}
        <i class="fa-regular fa-file-excel"></i>
        
      {% elif post.get_file_ext == 'jpg' or post.get_file_ext == 'jpeg' or post.get_file_ext == 'png'}
        <i class="fa-regular fa-file-image"></i>
      {% else %}
        <i class="far fa-file"></i>
      {% endif %}
      {{ post.get_file_name }}
        </a>
    {% endif %}
      
  </article>
</div>
<!-- Comments section-->
<section class="mb-5 mt-3">
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
            <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
            <!-- Comment with nested comments-->
            <div class="d-flex mb-4">
                <!-- Parent comment-->
                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                    <!-- Child comment 1-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                        </div>
                    </div>
                    <!-- Child comment 2-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            When you put money directly to a problem, it makes a good headline.
                        </div>
                    </div>
                </div>
            </div>
            <!-- Single comment-->
            <div class="d-flex">
                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

day73__/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

<!-- Featured blog post-->
{% block main_area %}
{% for post in post_list %}
<div class="card mb-4">
    {% if post.head_image %}
    <a href="#!"><img class="card-img-top" src="{{post.head_image}}" alt="..." /></a>
    {% else %}
    <a href="#!"><img class="card-img-top" src="https://picsum.photos/seed/{{post.id}}/600/300" alt="..." /></a>
    {% endif %}
    <div class="card-body">
        <div class="small text-muted">{{ post.created_at }}</div>
        <h2 class="card-title">{{ post.title }}</h2>
        {% if post.hook_text %}
            <h5 class="text-muted"> {{ post.hook_text }}</h5>
        {% endif %}
        <p class="card-text">{{ post.content | truncatewords:50}}</p>
        <a class="btn btn-primary" href="{{ post.get_absolute_url }}">Read more →</a>
    </div>
</div>
{% endfor %}
<!-- Pagination-->
<nav aria-label="Pagination">
    <hr class="my-0" />
    <ul class="pagination justify-content-center my-4">
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&larr; Newer</a></li>
        <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
        <li class="page-item"><a class="page-link" href="#!">2</a></li>
        <li class="page-item"><a class="page-link" href="#!">3</a></li>
        <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
        <li class="page-item"><a class="page-link" href="#!">15</a></li>
        <li class="page-item"><a class="page-link" href="#!">Older &rarr;</a></li>
    </ul>
</nav>
{% endblock %}