day75/blog/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("category/<str:slug>", views.category_page),   # 127.0.0.1/blog/cat
    path("<int:pk>", views.PostDetail.as_view()),   # 127.0.0.1/blog/1
    path("", views.PostList.as_view())              # 127.0.0.1/blog/
]

day75/do_it_django_prj/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("news/", include("news.urls")),
    path("blog/", include("blog.urls")),
    path("admin/", admin.site.urls),
    path("", include("single_pages.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

day75/news/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("<int:pk>", views.PostDetail.as_view()),   # 127.0.0.1/blog/1
    
    path("", views.PostList.as_view())
]


# FBV, CBV

day75/single_pages_asd/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("about_me", views.about_me),
    path("", views.landing)
]

day75/blog/models.py
from django.db import models
from django.contrib.auth.models import User

import os


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=100, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().rsplit('.', maxsplit=1)[-1]

day75/news/models.py
from django.db import models
from django.contrib.auth.models import User
# from blog.models import Post as ps
import os


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=100, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/news/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'

# Create your models here.
class NewsPost(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    name = models.CharField(max_length=10)
    hook_text = models.CharField(max_length=100, blank=True)

    email = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    head_image = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True)
    # author = ps.author
    # category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)

    author_news = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category_news = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk - 1}]{self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/news/{self.pk}'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().rsplit('.', maxsplit=1)[-1]

day75/single_pages_asd/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    write_time = models.DateTimeField()
    content = models.TextField()
    # name = models.CharField(max_length=30)
    # email = models.CharField(max_length=30)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f'[{self.pk}]{self.title}'

day75/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post, Category

# Create your views here.
# def index(reqeust):
#     posts = Post.objects.all().order_by('-pk')

#     return render(
#         reqeust,
#         "blog/index.html",
#         {
#             "posts": posts,
#         }
#     )


# def single_post_page(reqeust, pk):
#     post = Post.objects.get(pk=pk)

#     return render(
#         reqeust,
#         "blog/single_post_page.html",
#         {
#             "post": post,
#         }
#     )


def category_page(reqeust, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        reqeust,
        "blog/post_list.html",
        {
            "post_list": post_list,
            "categories": Category.objects.all(),
            "no_category_post_count": Post.objects.filter(category=None).count(),
            "category": category,
        }
    )


class PostList(ListView):
    model = Post
    ordering = "-pk"

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()

        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()

        return context

day75/news/views.py
from django.shortcuts import render
from .models import Post, Category
from django.views.generic import ListView, DetailView

# Create your views here.
# def index(request):
#     posts = Post.objects.all()
#     return render(
#         request,
#         "news/index.html",
#         {
#             "posts": posts,
#         }
#     )

def category_page(reqeust, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        reqeust,
        "news/post_list.html",
        {
            "post_list": post_list,
            "categories": Category.objects.all(),
            "no_category_post_count": Post.objects.filter(category=None).count(),
            "category": category,
        }
    )
class PostList(ListView):
    model = Post
    ordering = "-pk"

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()

        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()

        return context
    

day75/single_pages/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
    return render(
        request,
        "single_pages/landing.html",
    )

def about_me(request):
    return render(
        request,
        "single_pages/about_me.html",
    )

day75/single_pages_asd/views.py
from django.shortcuts import render

# Create your views here.

def about_me(request):
    return render(
        request,
        'single_pages/landing.html',
    )

def landing(request):
    return render(
        request,
        'single_pages/about_me.html',
    )

day75/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>{% block head_title %}Blog{% endblock %}</title>
        <script src="https://kit.fontawesome.com/6169945903.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
    </head>
    <body>
        <!-- Responsive navbar-->
        <!-- navbar.html로 nav module 구성 후 load -->
        {% include 'blog/navbar.html' %}

        <!-- Page header with logo and tagline-->
        <!-- <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Blog Home</h1>
                    <p class="lead mb-0">네이버 뉴스</p>
                </div>
            </div>
        </header> -->

        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8" id="main-area">
                    <!-- Featured blog post-->
                    {% block main_area %}
                    {% endblock %}
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4" id="categories-card">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <ul class="list-unstyled mb-0">
                                    {% for category in categories %}
                                    <li>
                                        <a href="{{ category.get_absolute_url }}">{{ category }} ({{category.post_set.count}})</a>
                                    </li>
                                    {% endfor %}
                                    <li>
                                        <a href="/blog/category/no_category">미분류 ({{ no_category_post_count }})</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer.html로 footer module 구성 후 load -->
        {% include 'blog/footer.html' %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

day75/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}

{% block main_area %}
<!-- Post content-->
<div id="post-area">
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1 mt-4">{{ post.title }}</h1>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">{{ post.created_at }}</div>
            <!-- Post categories-->
            <a class="badge bg-secondary text-decoration-none link-light" href="#!"> {{ post.category.name }} </a>
            <!-- Author -->
            <p class="lead">
                작성자
                <a href="#">{{ post.author | upper }}</a>
            </p>
        </header>
        <!-- Preview image figure-->
        {% if post.head_image %}
            <figure class="mb-4"><img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="..." /></figure>                            
        {% else %}
            <figure class="mb-4"><img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.id}}/600/300" alt="..." /></figure>
        {% endif %}
        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4"> {{post.content}} </p>
        </section>                        
        <!-- download button -->
        {% if post.file_upload %}
            <a type="button" href="{{ post.file_upload.url }}">Download: 
                <!-- zip -->
                {% if post.get_file_ext == 'zip' %}
                <i class="fa-solid fa-file-zipper"></i> 
                <!-- excel, csv -->
                {% elif post.get_file_ext == 'csv' or post.get_file_ext == 'xls' or post.get_file_ext == 'xlsx' %}
                    <i class="fa-solid fa-file-excel"></i>                        
                <!-- jpg, jpeg, png -->
                {% elif post.get_file_ext == 'jpg' or post.get_file_ext == 'jpeg' or post.get_file_ext == 'png' %}
                    <i class="fa-regular fa-file-image"></i>
                <!-- else -->
                {% else %}
                    <i class="far fa-file"></i>
                {% endif %}
                {{ post.get_file_name }}
            </a>
        {% endif %}
    </article>
</div>
<hr>
<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
            <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
            <!-- Comment with nested comments-->
            <div class="d-flex mb-4">
                <!-- Parent comment-->
                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                    <!-- Child comment 1-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                        </div>
                    </div>
                    <!-- Child comment 2-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            When you put money directly to a problem, it makes a good headline.
                        </div>
                    </div>
                </div>
            </div>
            <!-- Single comment-->
            <div class="d-flex">
                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

day75/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}


<!-- Featured blog post-->
{% block main_area %}
<h1>Blog {% if category %}<span class="badge text-bg-secondary">{{ category }}</span>{% endif %}</h1>
{% if post_list.exists %}
{% for post in post_list %}
<div class="card mb-4" id="post-{{ post.pk }}">
    {% if post.head_image %}
        <a href="#!"><img class="card-img-top" src="{{ post.head_image.url }}" alt="..." /></a>
    {% else %}
        <a href="#!"><img class="card-img-top" src="https://picsum.photos/seed/{{post.id}}/600/300" alt="..." /></a>
    {% endif %}
    <div class="card-body">
        {% if post.category %}
            <span class="badge badge-secondary float-right">{{ post.category }}</span>
        {% else %}
            <span class="float-right">미분류</span>
        {% endif %}
        <div class="small text-muted">{{ post.created_at }}</div>
        <div class="small text-muted">
            작성자
            <a href="#">{{ post.author | upper }}</a>
        </div>
        <h2 class="card-title">{{ post.title }}</h2>
        {% if post.hook_text %}
            <h5 class="text-muted">{{ post.hook_text }}</h5>
        {% endif %}
        <p class="card-text">{{ post.content | truncatewords:50}} </p>
        <a class="btn btn-primary" href="{{ post.get_absolute_url }}">Read more →</a>
    </div>
</div>
{% endfor %}
{% else %}
<div>
    <p>아직 게시물이 없습니다.</p>
</div>
{% endif %}
<!-- Pagination-->
<nav aria-label="Pagination">
    <hr class="my-0" />
    <ul class="pagination justify-content-center my-4">
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&larr; Newer</a></li>
        <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
        <li class="page-item"><a class="page-link" href="#!">2</a></li>
        <li class="page-item"><a class="page-link" href="#!">3</a></li>
        <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
        <li class="page-item"><a class="page-link" href="#!">15</a></li>
        <li class="page-item"><a class="page-link" href="#!">Older &rarr;</a></li>
    </ul>
</nav>
{% endblock %}

day75/news/templates/news/post_detail.html
{% extends 'blog/base.html' %}

{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}

{% block main_area %}
<!-- Post content-->
<div id="post-area">
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1 mt-4">{{ post.title }}</h1>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">{{ post.created_at }}</div>
            <!-- Post categories-->
            <a class="badge bg-secondary text-decoration-none link-light" href="#!">정치</a>
            <!-- Author -->
            <p class="lead">
                by
                <a href="#">TBC</a>
            </p>
        </header>
        <!-- Preview image figure-->
        {% if post.head_image %}
            <figure class="mb-4"><img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="..." /></figure>                            
        {% else %}
            <figure class="mb-4"><img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.id}}/600/300" alt="..." /></figure>
        {% endif %}
        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4"> {{post.content}} </p>
        </section>                        
        <!-- download button -->
        {% if post.file_upload %}
            <a type="button" href="{{ post.file_upload.url }}">Download: 
                <!-- zip -->
                {% if post.get_file_ext == 'zip' %}
                <i class="fa-solid fa-file-zipper"></i> 
                <!-- excel, csv -->
                {% elif post.get_file_ext == 'csv' or post.get_file_ext == 'xls' or post.get_file_ext == 'xlsx' %}
                    <i class="fa-solid fa-file-excel"></i>                        
                <!-- jpg, jpeg, png -->
                {% elif post.get_file_ext == 'jpg' or post.get_file_ext == 'jpeg' or post.get_file_ext == 'png' %}
                    <i class="fa-regular fa-file-image"></i>
                <!-- else -->
                {% else %}
                    <i class="far fa-file"></i>
                {% endif %}
                {{ post.get_file_name }}
            </a>
        {% endif %}
    </article>
</div>
<hr>
<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
            <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
            <!-- Comment with nested comments-->
            <div class="d-flex mb-4">
                <!-- Parent comment-->
                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                    <!-- Child comment 1-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                        </div>
                    </div>
                    <!-- Child comment 2-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            When you put money directly to a problem, it makes a good headline.
                        </div>
                    </div>
                </div>
            </div>
            <!-- Single comment-->
            <div class="d-flex">
                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                </div>
            </div>
        </div>
    </div>
</section>
<!-- <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{{post.title}} - Blog</title>
    </head>
    <body>
        <nav>
            <a href="/blog/">Blog</a>
        </nav>

        <h1>{{post.title}}</h1>
        <h4>{{post.created_at}}</h4>
        <p>{{post.content}}</p>
        <hr>
        <h3>(댓글 추가 예정)</h3> 
    </body>
</html> -->


{% endblock %}

day75/news/templates/news/post_list.html
{% extends 'blog/base.html' %}

{% block main_area %}
<h1>News {% if category %}<span class="badge text-bg-secondary">{{ category }}</span>{% endif %}</h1>

{% if post_list.exists %}
    
    <!-- Featured blog post-->
{% for post in post_list %}
<div class="card mb-2" id="post-{{ post.pk }}">
    <div class="row">
        <div class="col-lg-4">
            <a href="#!"><img class="card-img-top" src="https://dummyimage.com/850x350/dee2e6/6c757d.jpg" alt="..."></a>
        </div>
        <div class="col-lg-8">
            <div class="card-body">
            {% if post.category %}
                <span class="badge badge-secondary float-right">{{ post.category }}</span>
            {% else %}
                <span class="float-right">미분류</span>
            {% endif %}
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">{{ post.content | truncatewords:20 }}</p>
                <p class="card-text">{{ post.name }}</p>
                <div class="small text-muted">
                    작성자
                    <a href="#">{{ post.author | upper }}</a>
                </div>
                <!-- <a class="btn btn-primary" href="#!">Read more →</a> -->
                <a class="btn btn-primary" href="{{ post.get_absolute_url }}">Read more →</a>

            </div>
        </div>
    </div>
</div>
    {% endfor %}
    <!-- Pagination-->
<nav aria-label="Pagination">
    <hr class="my-0" />
    <ul class="pagination justify-content-center my-4">
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&larr; Newer</a></li>
        <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
        <li class="page-item"><a class="page-link" href="#!">2</a></li>
        <li class="page-item"><a class="page-link" href="#!">3</a></li>
        <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
        <li class="page-item"><a class="page-link" href="#!">15</a></li>
        <li class="page-item"><a class="page-link" href="#!">Older &rarr;</a></li>
    </ul>
</nav>
{% else %}
    <h3> 아직 게시물이 없습니다.</h3.>
{% endif %}
{% endblock %}

day75/single_pages/templates/single_pages/landing.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Hello~. This is my first django project</title>
    </head>
    <body>
        <nav>
            <a href="/blog/">Blog</a>
            <a href="/about_me/">About me</a>
        </nav>

        <h1>Hello. I'm jihwan.</h1>
        <h2>This is a landing page.</h2>
        <h3>Building...</h3>
    </body>
</html>

day75/single_pages_asd/templates/single_pages/landing.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Hello~ This is my first django project</title>
    </head>
    <body>
        <nav>
            <a href="/blog/">Blog</a>
            <a gref="/about_me/">About_me</a>
        </nav>

        <h1> Hello. I'm jihwan. </h1>
        <h2> landing page </h2>
        <h3> Building... </h3>
    </body>
</html>